### ISSUE TITLE
line breaks, text size, etc.

### ISSUE THREAD

**Issue by prism2001** [bquenin/interpreter#9]
i really like the idea of this program, seems promising so far. however unfortunately it's pretty unusable in its current state. i tried to translate this dialogue from a game but the only a portion of the translated text is visible. it gets cut off because it's putting it all in one line like this:

![translated text](https://ptpimg.me/3iru30.png)

for context, here's what the game was displaying:

![game](https://ptpimg.me/678k6e.png)

i think more customization for the output text would help a lot to make this usable. line breaks are definitely something i think this program needs to avoid issues like this, as well as changing the size of the text to allow more text to fit on the screen. ideally the program could maybe overlay itself over the JP text and try to match the original text in size and position (similar to the way Google's mobile app does when you scan text) but i'm not sure how complex that would be to implement

**Comment by bquenin** [comment]
@prism2001 you're absolutely right. I will work on a fix for the text to be bounded in the window. I will also add some parameters for the font size. Regarding text placement, this could be done in another PR.

**Comment by bquenin** [comment]
@prism2001 please let me know if release 1.1.0 (https://github.com/bquenin/interpreter/releases/tag/v1.1.0) is more usable

**Comment by prism2001** [comment]
> @prism2001 please let me know if release 1.1.0 (https://github.com/bquenin/interpreter/releases/tag/v1.1.0) is more usable

getting this error:
![image](https://user-images.githubusercontent.com/11824514/181512305-00a2ccc9-7c57-4076-ac37-9371cddcdec8.png)

**Comment by bquenin** [comment]
Let me look into this

**Comment by bquenin** [comment]
@prism2001 Can you check with release 1.2.0?
You should now be able to move and resize the window to your convenience. Once it's done, you can toggle the window by pressing 'T'.
I also added the explanation for the false positive virus scan in the README.

**Comment by prism2001** [comment]
> @prism2001 Can you check with release 1.2.0, https://github.com/bquenin/interpreter/releases/tag/v1.2.0 ? You should now be able to move and resize the window to your convenience. Once it's done, you can toggle the window by pressing 'T'. I also added the explanation for the false positive virus scan in the README.

this is much better! thank you for the speedy fix :)

**Comment by bquenin** [comment]
no worries, thanks for your feedback! It helps me better understand the usage.
